services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prisma_app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://app:app@db:3306/prisma_app
      CORS_ORIGIN: http://localhost:5173
      JWT_SECRET: supersecret
      PORT: 3000
      DB_HOST: db
      DB_USER: app
      DB_PASS: app
      DB_NAME: prisma_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/server/uploads

volumes:
  dbdata: